on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to Docs
        run: curl -X POST -d {} ${{ secrets.DEPLOY_DOCS_URL }}